import { scrypt, randomBytes } from 'crypto';
import { promisify } from 'util';

const scryptAsync = promisify(scrypt);

/**
 * Hashes a plaintext password securely using Node's native crypto scrypt with a unique salt.
 * @param password Plaintext password to hash
 * @returns A string in the format salt:derivedKeyHex
 */
export async function hashPassword(password: string): Promise<string> {
  const salt = randomBytes(16).toString('hex');
  const derivedKey = (await scryptAsync(password, salt, 64)) as Buffer;
  return `${salt}:${derivedKey.toString('hex')}`;
}

/**
 * Verifies a plaintext password against a previously generated secure hash.
 * @param password Plaintext password to verify
 * @param combinedHash Secure hash generated by hashPassword in the format salt:derivedKeyHex
 * @returns true if verified successfully, false otherwise
 */
export async function verifyPassword(password: string, combinedHash: string): Promise<boolean> {
  try {
    const [salt, key] = combinedHash.split(':');
    if (!salt || !key) return false;
    const derivedKey = (await scryptAsync(password, salt, 64)) as Buffer;
    return derivedKey.toString('hex') === key;
  } catch (error) {
    console.error('Password verification failed:', error);
    return false;
  }
}
